FROM gcr.io/google.com/cloudsdktool/cloud-sdk:543.0.0-alpine

RUN curl -L -o /usr/bin/opa https://openpolicyagent.org/downloads/v1.9.0/opa_linux_amd64_static

RUN chmod +x /usr/bin/opa

CMD ["/bin/bash"]
