ARG CLOUD_SDK_VERSION=558.0.0
ARG OPA_VERSION=1.14.0

FROM gcr.io/google.com/cloudsdktool/cloud-sdk:${CLOUD_SDK_VERSION}-alpine

ARG OPA_VERSION

RUN wget -q -O /usr/bin/opa "https://github.com/open-policy-agent/opa/releases/download/v${OPA_VERSION}/opa_linux_amd64_static" && \
    chmod +x /usr/bin/opa

CMD ["/bin/bash"]
