apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: compliance-analysis
  labels:
    cloud.googleapis.com/location: northamerica-northeast1
  annotations:
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/container-dependencies: '{"cac-python-1":["git-sync-1"],"opa-1":["git-sync-1"]}'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: cac-solution-37505682288-sa@cacv2-devproj.iam.gserviceaccount.com
      containers:
      - name: cac-python-1
        image: northamerica-northeast1-docker.pkg.dev/cacv2-devproj/cac-python/cac-python:432552
        ports:
        - name: http1
          containerPort: 8443
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: GCP_PROJECT
          value: "cacv2-devproj"
        - name: ORG_NAME
          value: "lab-rat.ca"
        - name: ORG_ID
          value: "37505682288"
        - name: GCS_BUCKET
          value: ""
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
      - name: git-sync-1
        image: "northamerica-northeast1-docker.pkg.dev/cacv2-devproj/gitsync/git-sync:v4.2.3"
        env:
        - name: GITSYNC_HTTP_BIND
          value: ':9080'
        - name: GITSYNC_REPO
          value: "https://source.developers.google.com/p/gcp-cac-solution-build/r/cac_policies"
        - name: GITSYNC_ROOT
          value: '/mnt/policies/git'
        - name: GITSYNC_REF
          value: "feat/enhancement"
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: policies
          mountPath: /mnt/policies
        startupProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 5
          httpGet:
            path: /
            port: 9080
      - name: opa-1
        image: "northamerica-northeast1-docker.pkg.dev/cacv2-devproj/opa/opa:0.70.0"
        args:
        - --server
        - --addr
        - :8181
        - -d
        - /mnt/policies/git/policies
        env:
        - name: GR11_04_ORG_ID
          value: "37505682288"
        - name: GR01_03_DOMAIN
          value: ""
        - name: GR02_01_DOMAIN
          value: ""
        - name: GR01_06_PRIVILEGED_USERS
          value: "user:jenn@lab-rat.ca"
        - name: GR01_06_REGULAR_USERS
          value: "  "
        - name: GR02_01_PRIVILEGED_USERS
          value: "user:jenn@lab-rat.ca"
        - name: GR02_01_REGULAR_USERS
          value: "  "
        - name: GR02_08_ALLOWED_DOMAINS
          value: "lab-rat.ca,pwc.com "
        - name: GR02_08_DENY_DOMAINS
          value: "  "
        - name: GR02_09_HAS_GUEST_USERS
          value: "False"
        - name: GR02_10_HAS_GUEST_USERS
          value: "False"
        - name: GR03_01_CUSTOMER_IDS
          value: "  "
        - name: GR03_01_ALLOWED_CIDRS
          value: "  "
        - name: GR05_01_SECURITY_CATEGORY_KEY
          value: "SECURITY_CATEGORY"
        - name: GR07_03_ALLOWED_CA_ISSUERS
          value: "Let's Encrypt,Verisign "
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: policies
          mountPath: /mnt/policies
      volumes:
      - name: policies
        emptyDir:
          medium: Memory
          sizeLimit: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
