apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: opapipeline
description: Compliance check app delivery pipeline
serialPipeline:
  stages:
    - targetId: development
      profiles: [dev]
      strategy:
        standard:
          verify: false

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: development
description: Cloud Run development service
run:
  location:
